const EVENTS = {
  connection: 'connection',
  CLIENT: {
    JOIN_SERVER: 'JOIN_SERVER',
      JOIN_DEVICE_ROOM: 'JOIN_DEVICE_ROOM',
      LEAVE_DEVICE_ROOM: 'LEAVE_DEVICE_ROOM',
      DESTROY_CLIENT: 'DESTRYO_CLIENT'
  },
  SERVER: {
      JOINED_SERVER: 'JOINED_SERVER',
      DEVICE_ADD_SUCCESS: 'DEVICE_ADD_SUCCESS',
      DEVICE_REMOVE_SUCCESS: 'DEVICE_REMOVE_SUCCESS',
      SEND_CLIENT_DATA: 'SEND_CLIENT_DATA',
      SEND_DEVICE_DATA: 'SEND_DEVICE_DATA',
      REMOVE_FROM_DEVICE_ROOM: 'REMOVE_FROM_DEVICE_ROOM'
  }
};
export default EVENTS;