export const ADD_DEVICE = 'ADD_DEVICE';
export const UPDATE_DEVICE_DATA = 'UPDATE_DEVICE_DATA';
export const REMOVE_DEVICE = 'REMOVE_DEVICE';
export const GET_DEVICE_DATA = 'GET_DEVICE_DATA';
export const GET_UPDATED_TIME = 'GET_UPDATED_TIME';
export const UPDATE_UPDATED_TIME = 'UPDATE_UPDATED_TIME';